spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    display-request-duration: true
  api-docs:
    path: /api-docs

admin:
  token: ${ADMIN_TOKEN}